language: java
jdk:
   - oraclejdk8
notifications:
  email: false
branches:
   only:
     - master
     - stable
deploy:
  - provider: releases
    api_key: "8826c523aeefb8c21e3e2bdc1dd6a7a56e74a025"
    file: "/home/travis/build/arturmalinowski/project-Edmund/edmund-core/target/project-Edmund.jar"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
  - provider: s3
    access_key_id: "AKIAIRQPLCULWHZ4MRTA"
    secret_access_key: "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"
    bucket: "project-edmund"
    skip_cleanup: true
    acl: public_read
    local_dir: "/home/travis/build/arturmalinowski/project-Edmund/edmund-core/target/project-Edmund.jar"
